# Prod config
services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: forme
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - '27019:27017'
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: forme
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
  app:
    container_name: app-spring
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/market
      SPRING_DATASOURCE_USERNAME: salman
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
